### ISSUE TITLE
I want a dropdown that contains Core Content on a lesson

### ISSUE THREAD

**Issue by jack-skerrett-oak** [oaknational/Oak-Web-Application#1199]
We will want to be able to display more information on the lesson overview page without taking away the path that directs users to the slide deck 
https://www.figma.com/file/hQoMOEvJQlDJZ0n2ehftVT/Beta?type=design&node-id=3507-267596&t=iZLDK1jcdBPaVYMK-4

**Acceptance Criteria:**
- [x] Introduce the "Lesson overview" dropdown
- [x] Display the current "core content" data that is at the top, in this component
    - Display in whatever format the data comes in, don't worry about morphing it into a bullet pointed list (unless it is in a bullet pointed list) 
    - I think core content is the only extra info we currently display at the top of a lesson... 
- [x] If there is no core content, or any extra additional fields (there will be more later), then don't display this drop down (there should always be something here though)
- [x] Remove core content from the top of the page
- [x] Collapsed on page load

**Comment by Monika-Koziol** [comment]
Note on designs
After reviewing it with @k-huggs we made the content of the container more consistent with the content of the other accordions (e.g. quiz). So we matched the backgrounds (to white) and text size to 24px H5. Figma is out of date.
