### ISSUE TITLE
Quiz styling - Short Answer inline

### ISSUE THREAD

**Issue by verityroberts** [oaknational/Oak-Web-Application#1285]
![Image](https://user-images.githubusercontent.com/102532470/231432515-d70b2b66-0d4c-4017-825a-83c3241f8687.png)

Example (Exit quiz Q4):
https://owa.thenational.academy/beta/teachers/key-stages/ks3/subjects/maths/units/expressions-equations-and-inequalities-7d65/lessons/exploring-equality-60rkac

---
**Acceptance Criteria:**
- [x] Short answer inline questions should have a styled component denoting where the answer goes instead of the {{}}
Additional background context - in the pupil experience it would be a box to type in

(https://www.figma.com/file/hQoMOEvJQlDJZ0n2ehftVT/Beta?type=design&node-id=2792-521490&t=mzTF8N24h67OoxzJ-4)

**Comment by k-huggs** [comment]
Just looking at this do we want to have the underlines consistent across the site? 

![Image](https://github.com/oaknational/Oak-Web-Application/assets/91190841/15f43ba5-f3f7-4c0a-85c3-d6b14bb9aba7)
