### ISSUE TITLE
"aria expanded" on expandable components across the site

### ISSUE THREAD

**Issue by jack-skerrett-oak** [oaknational/Oak-Web-Application#1367]
It will allow screen reader users to anticipate more content will be shown when this is selected

This has already been implemented by someone on the expandable mobile menus in webinar listing etc

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded

---
**Acceptance Criteria:**
- Add aria-expanded functionality to anything that expands
    - [x] Lesson overview components
    - [ ] Hamburger menu
    - [ ] About us bio modal buttons
    - [ ] Check if there is anywhere else?

**Comment by JBR90** [comment]
Lesson overview in this PR - https://github.com/oaknational/Oak-Web-Application/pull/1643
