### ISSUE TITLE
I want a subject search filter

### ISSUE THREAD

**Issue by jack-skerrett-oak** [oaknational/Oak-Web-Application#1584]
Almost identical filter (to ks) that will go into elastic query
Some possible refactoring to make filtering more generic

**Acceptance Criteria:**
- [ ] Display a list of checkboxes, one for every subject in all key stages (no duplicates)
- [ ] No EYFS, specialist subjects
- [ ] Click a filter, acts like KS filter but for subjects!
- [ ] Index elastic - set subject slug as keyword so that it is not analysed (hyphens removed)

**Comment by JBR90** [comment]
@verityroberts & @jack-skerrett-oak - unfortunately I have had to make a small change to acorn index for these to work with hyphenated subject slugs - i've updated the acceptance criteria
