### ISSUE TITLE
Render Science Lesson Images

### ISSUE THREAD

**Issue by k-huggs** [oaknational/Oak-Web-Application#1618]
Currently some science lessons are not rendering the quiz images, this is due to additional text being inserted after the the url, which is causing the images to break.

An example being the exit quiz for the following:  

https://deploy-preview-1609--oak-web-application.netlify.thenational.academy/beta/teachers/programmes/chemistry-secondary-ks4/units/atomic-structure-and-the-periodic-table-u68nqqc/lessons/atoms-elements-and-compounds-h3hasv

/beta/teachers/programmes/chemistry-secondary-ks4/units/atomic-structure-and-the-periodic-table-u68nqqc/lessons/atoms-elements-and-compounds-h3hasv

We'll need to remove this text so that the images will render correct. Plug new MV's into OWA

**Comment by k-huggs** [comment]
![Image](https://github.com/oaknational/Oak-Web-Application/assets/91190841/17429546-13e9-4275-b532-a1fe78257c93)

**Comment by jack-skerrett-oak** [comment]
feature branch
