### ISSUE TITLE
Spike Ticket: OakErrors Integration and Usage

### ISSUE THREAD

**Issue by JBR90** [oaknational/Oak-Web-Application#1623]
Timebox: half a day, if we need more we can do more later

Start with downloads

**Acceptance Criteria:**

- [ ] Identify and list the files where OakErrors should be implemented in a ticket
- [ ] Identify and list where errors are used when they should be Oak Errors in a ticket

**Comment by benprotheroe** [comment]
https://www.notion.so/oaknationalacademy/Check-Server-Side-Error-Reporting-1416-c99fc3da58024be98fcf7c805475b9f5#ba9e213939444c6d9a3a6893bb7b1f21

**Comment by andykwoods** [comment]
Is this is in this Sprint, can it be estimated please?

**Comment by jack-skerrett-oak** [comment]
@andykwoods it was a time-boxed investigation to half a day
